# -*- coding: utf-8 -*-
import http.server
import socketserver
import webbrowser
import sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace') if hasattr(sys.stdout, 'reconfigure') else None
import urllib.request
import urllib.error
import urllib.parse
import json
import os
import io
import tempfile

# Ensure the server runs from the directory where this script is located
os.chdir(os.path.dirname(os.path.abspath(__file__)))

PORT = 8000

# --- THEME MANAGEMENT ---
THEMES = {
    "orbian":    {"p": (99,102,241), "s": (15,23,42), "t": (51,65,85), "l": (248,250,252), "hp": "6366f1", "hs": "0f172a"},
    "emerald":  {"p": (16,185,129), "s": (6,78,59),  "t": (6,78,59),  "l": (236,253,245), "hp": "10b981", "hs": "064e3b"},
    "rose":     {"p": (225,29,72),  "s": (76,5,25),  "t": (76,5,25),  "l": (255,241,242), "hp": "e11d48", "hs": "4c0519"},
    "midnight": {"p": (148,163,184), "s": (0,0,0),    "t": (248,250,252), "l": (30,41,59), "hp": "94a3b8", "hs": "000000"},
    "amber":    {"p": (245,158,11), "s": (69,26,3),  "t": (69,26,3),  "l": (255,251,235), "hp": "f59e0b", "hs": "451a03"},
}

def get_theme(data):
    name = str(data.get("theme", "orbian")).lower()
    return THEMES.get(name, THEMES["orbian"])

# --- Python PPTX Generator ---
def generate_pptx_bytes(data):
    """Generate a polished .pptx file in memory and return bytes."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    t = get_theme(data)
    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # ── COLOR PALETTE ──────────────────────────────────────────────
    C_DARK   = RGBColor(*t["s"])
    C_ACCENT = RGBColor(*t["p"])
    C_WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
    C_LIGHT  = RGBColor(*t["l"])
    C_TEXT   = RGBColor(*t["t"])

    blank_layout = prs.slide_layouts[6]

    # ── SLIDE 1: TITLE ─────────────────────────────────────────────
    slide = prs.slides.add_slide(blank_layout)
    bg = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    bg.fill.solid(); bg.fill.fore_color.rgb = C_DARK; bg.line.fill.background()

    bar = slide.shapes.add_shape(1, 0, 0, Inches(0.25), prs.slide_height)
    bar.fill.solid(); bar.fill.fore_color.rgb = C_ACCENT; bar.line.fill.background()

    bot = slide.shapes.add_shape(1, 0, Inches(7.0), prs.slide_width, Inches(0.5))
    bot.fill.solid(); bot.fill.fore_color.rgb = C_ACCENT; bot.line.fill.background()

    tx_box = slide.shapes.add_textbox(Inches(0.6), Inches(2.5), Inches(12), Inches(1.5))
    tf = tx_box.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]; p.alignment = PP_ALIGN.LEFT
    run = p.add_run(); run.text = data.get("title", "Orbian Presentation")
    run.font.bold = True; run.font.size = Pt(44); run.font.color.rgb = C_WHITE

    sub_box = slide.shapes.add_textbox(Inches(0.6), Inches(4.1), Inches(10), Inches(0.8))
    stf = sub_box.text_frame; sp = stf.paragraphs[0]
    sr = sp.add_run(); sr.text = data.get("subtitle", "Generated by Orbian AI")
    sr.font.size = Pt(20); sr.font.color.rgb = C_ACCENT

    foot = slide.shapes.add_textbox(Inches(0.6), Inches(7.05), Inches(12), Inches(0.3))
    ftf = foot.text_frame; fp = ftf.paragraphs[0]; fp.alignment = PP_ALIGN.LEFT
    fr = fp.add_run(); fr.text = f"ORBIAN INTELLIGENCE PLATFORM  •  DESIGN THEME: {data.get('theme','orbian').upper()}"
    fr.font.size = Pt(9); fr.font.color.rgb = C_WHITE; fr.font.bold = True

    # ── CONTENT SLIDES ─────────────────────────────────────────────
    for slide_data in data.get("slides", []):
        slide = prs.slides.add_slide(blank_layout)
        wbg = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
        wbg.fill.solid(); wbg.fill.fore_color.rgb = C_LIGHT; wbg.line.fill.background()

        header_bar = slide.shapes.add_shape(1, 0, 0, prs.slide_width, Inches(1.3))
        header_bar.fill.solid(); header_bar.fill.fore_color.rgb = C_DARK; header_bar.line.fill.background()

        acc_stripe = slide.shapes.add_shape(1, 0, Inches(1.1), prs.slide_width, Inches(0.2))
        acc_stripe.fill.solid(); acc_stripe.fill.fore_color.rgb = C_ACCENT; acc_stripe.line.fill.background()

        side_bar = slide.shapes.add_shape(1, Inches(0.4), Inches(1.6), Inches(0.08), Inches(5.4))
        side_bar.fill.solid(); side_bar.fill.fore_color.rgb = C_ACCENT; side_bar.line.fill.background()

        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.15), Inches(12), Inches(0.9))
        ttf = title_box.text_frame; tp = ttf.paragraphs[0]; tp.alignment = PP_ALIGN.LEFT
        tr = tp.add_run(); tr.text = slide_data.get("title", "Slide")
        tr.font.bold = True; tr.font.size = Pt(28); tr.font.color.rgb = C_WHITE

        content = slide_data.get("content", [])
        if isinstance(content, str): content = [l.strip() for l in content.split("\n") if l.strip()]

        content_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.6), Inches(11.8), Inches(5.5))
        ctf = content_box.text_frame; ctf.word_wrap = True
        for i, point in enumerate(content):
            cp = ctf.paragraphs[0] if i == 0 else ctf.add_paragraph()
            cp.space_before = Pt(8); cp.space_after = Pt(4)
            cr = cp.add_run(); cr.text = f"▸  {point}"; cr.font.size = Pt(18); cr.font.color.rgb = C_TEXT

        pg_box = slide.shapes.add_textbox(Inches(12.1), Inches(6.9), Inches(1.0), Inches(0.4))
        pgp = pg_box.text_frame.paragraphs[0]; pgp.alignment = PP_ALIGN.RIGHT
        pgr = pgp.add_run(); pgr.text = f"{prs.slides.index(slide)}"
        pgr.font.size = Pt(10); pgr.font.color.rgb = RGBColor(0x94, 0xa3, 0xb8)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ─── PDF GENERATOR (reportlab) ────────────────────────────────────────────────
def generate_pdf_bytes(data):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    t = get_theme(data)
    NAVY   = colors.HexColor('#' + t["hs"])
    INDIGO = colors.HexColor('#' + t["hp"])
    SLATE  = colors.HexColor('#' + t["hs"]) # Using secondary for prominence
    LIGHT  = colors.HexColor('#' + (t["l"] if isinstance(t["l"], str) else "".join("%02x"%c for c in t["l"])))
    WHITE  = colors.white

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm, topMargin=2.5*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('OrbianTitle', fontName='Helvetica-Bold', fontSize=28, textColor=WHITE, leading=34, alignment=TA_LEFT, spaceAfter=6, backColor=NAVY)
    h2_style = ParagraphStyle('OrbianH2', fontName='Helvetica-Bold', fontSize=16, textColor=INDIGO, leading=20, spaceBefore=20, spaceAfter=8)
    body_style = ParagraphStyle('OrbianBody', fontName='Helvetica', fontSize=11, textColor=colors.HexColor('#334155'), leading=18, spaceAfter=6, leftIndent=12)
    bullet_style = ParagraphStyle('OrbianBullet', fontName='Helvetica', fontSize=11, textColor=colors.HexColor('#334155'), leading=18, spaceAfter=5, leftIndent=20, bulletIndent=8, bulletText='\u25b8')
    subtitle_style = ParagraphStyle('OrbianSub', fontName='Helvetica', fontSize=13, textColor=INDIGO, leading=18, spaceAfter=4)

    elements = []
    title_table = Table([[Paragraph(data.get('title','Orbian Document'), title_style)]], colWidths=[16.9*cm])
    title_table.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), NAVY), ('TOPPADDING', (0,0), (-1,-1), 22), ('BOTTOMPADDING', (0,0), (-1,-1), 22), ('LEFTPADDING', (0,0), (-1,-1), 20), ('RIGHTPADDING', (0,0), (-1,-1), 20)]))
    elements.append(title_table)
    elements.append(Spacer(1, 0.3*cm))
    elements.append(Paragraph(data.get('subtitle', 'Generated by Orbian AI'), subtitle_style))
    elements.append(HRFlowable(width='100%', thickness=2, color=INDIGO, spaceAfter=16))

    for i, slide in enumerate(data.get('slides', []), 1):
        elements.append(Paragraph(f"{i}. {slide.get('title','')}", h2_style))
        elements.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e2e8f0'), spaceAfter=8))
        content = slide.get('content', [])
        if isinstance(content, str): content = [l.strip() for l in content.split('\n') if l.strip()]
        for point in content: elements.append(Paragraph(point, bullet_style))
        elements.append(Spacer(1, 0.4*cm))

    elements.append(Spacer(1, 1*cm)); elements.append(HRFlowable(width='100%', thickness=1, color=INDIGO)); elements.append(Spacer(1, 0.2*cm))
    footer_style = ParagraphStyle('Footer', fontName='Helvetica', fontSize=8, textColor=colors.HexColor('#94a3b8'), alignment=TA_CENTER)
    elements.append(Paragraph(f'ORBIAN INTELLIGENCE PLATFORM  \u2022  THEME: {data.get("theme","ORBIAN").upper()}', footer_style))

    doc.build(elements)
    return buf.getvalue()


# ─── WORD GENERATOR (python-docx) ─────────────────────────────────────────────
def generate_docx_bytes(data):
    from docx import Document
    from docx.shared import Pt, Cm, RGBColor as DocxRGB
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    t = get_theme(data); doc = Document()
    for s in doc.sections: s.top_margin=Cm(2.5); s.bottom_margin=Cm(2); s.left_margin=Cm(2.5); s.right_margin=Cm(2.5)

    def set_para_bg(para, hex_color):
        pPr = para._p.get_or_add_pPr()
        shd = OxmlElement('w:shd'); shd.set(qn('w:val'), 'clear'); shd.set(qn('w:color'), 'auto'); shd.set(qn('w:fill'), hex_color)
        pPr.append(shd)

    def add_r(para, text, bold=False, size=11, rgb=(255,255,255)):
        run = para.add_run(text); run.bold = bold; run.font.size = Pt(size); run.font.color.rgb = DocxRGB(*rgb); return run

    title_p = doc.add_paragraph(); title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_bg(title_p, t["hs"]); add_r(title_p, data.get('title','Orbian Document'), bold=True, size=26)
    sub_p = doc.add_paragraph(); sub_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_bg(sub_p, t["hs"]); add_r(sub_p, data.get('subtitle','Generated by Orbian AI'), size=13, rgb=t["p"])
    doc.add_paragraph()

    for i, slide in enumerate(data.get('slides', []), 1):
        h = doc.add_heading(f"{i}. {slide.get('title','')}", level=2)
        h.runs[0].font.color.rgb = DocxRGB(*t["p"]); h.runs[0].font.size = Pt(14)
        content = slide.get('content', []);
        if isinstance(content, str): content = [l.strip() for l in content.split('\n') if l.strip()]
        for point in content:
            p = doc.add_paragraph(style='List Bullet'); p.paragraph_format.left_indent = Cm(0.5)
            r = p.add_run(point); r.font.size = Pt(11); r.font.color.rgb = DocxRGB(51, 65, 85)
        doc.add_paragraph()

    f_p = doc.add_paragraph(); f_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_r(f_p, f'ORBIAN INTELLIGENCE PLATFORM  \u2022  THEME: {data.get("theme","orbian").upper()}', size=8, rgb=(148, 163, 184))

    buf = io.BytesIO(); doc.save(buf); return buf.getvalue()


# ─── EXCEL GENERATOR (openpyxl) ───────────────────────────────────────────────
def generate_xlsx_bytes(data):
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    
    t = get_theme(data); wb = Workbook(); ws = wb.active; ws.title = "Orbian Data"
    NAVY = t["hs"]; INDIGO = t["hp"]; SLATE = '334155'; WHITE = 'FFFFFF'; LIGHT = t["hs"] # Use dark for head
    
    thin = Border(left=Side(style='thin', color='e2e8f0'), right=Side(style='thin', color='e2e8f0'), bottom=Side(style='thin', color='e2e8f0'), top=Side(style='thin', color='e2e8f0'))
    ws.column_dimensions['A'].width = 30; ws.column_dimensions['B'].width = 70; ws.column_dimensions['C'].width = 18

    ws.merge_cells('A1:C1'); c1 = ws['A1']; c1.value = data.get('title', 'Orbian Report')
    c1.font = Font(name='Calibri', size=18, bold=True, color=WHITE); c1.fill = PatternFill(fill_type='solid', fgColor=NAVY); c1.alignment = Alignment(horizontal='left', vertical='center', indent=2); ws.row_dimensions[1].height = 42

    ws.merge_cells('A2:C2'); c2 = ws['A2']; c2.value = data.get('subtitle', 'Generated by Orbian AI')
    c2.font = Font(name='Calibri', size=11, color=INDIGO, italic=True); c2.fill = PatternFill(fill_type='solid', fgColor=NAVY); c2.alignment = Alignment(horizontal='left', vertical='center', indent=2); ws.row_dimensions[2].height = 28

    headers = ['Slide / Section', 'Content / Detail', 'Category']
    for col, head in enumerate(headers, 1):
        cell = ws.cell(row=4, column=col, value=head)
        cell.font = Font(name='Calibri', size=11, bold=True, color=WHITE); cell.fill = PatternFill(fill_type='solid', fgColor=INDIGO); cell.alignment = Alignment(horizontal='center', vertical='center'); cell.border = thin
    ws.row_dimensions[4].height = 28

    current_row = 5
    for idx, slide in enumerate(data.get('slides', []), 1):
        ws.merge_cells(f'A{current_row}:C{current_row}')
        hc = ws.cell(row=current_row, column=1, value=f'{idx}. {slide.get("title","")}')
        hc.font = Font(name='Calibri', size=12, bold=True, color=SLATE); hc.fill = PatternFill(fill_type='solid', fgColor='f1f5f9'); hc.alignment = Alignment(horizontal='left', vertical='center', indent=1); hc.border = thin
        ws.row_dimensions[current_row].height = 24
        current_row += 1
        content = slide.get('content', [])
        if isinstance(content, str): content = [l.strip() for l in content.split('\n') if l.strip()]
        for j, point in enumerate(content):
            for col, val in enumerate(['', point, f'Point {idx}.{j+1}'], 1):
                cell = ws.cell(row=current_row, column=col, value=val)
                cell.font = Font(name='Calibri', size=11, color=SLATE); cell.fill = PatternFill(fill_type='solid', fgColor='FFFFFF' if j%2 else 'f8fafc'); cell.alignment = Alignment(vertical='center', wrap_text=True, indent=1); cell.border = thin
            ws.row_dimensions[current_row].height = 24; current_row += 1
        current_row += 1

    ws.merge_cells(f'A{current_row}:C{current_row}')
    f = ws.cell(row=current_row, column=1, value=f'ORBIAN PLATFORM • THEME: {data.get("theme","orbian").upper()}')
    f.font = Font(name='Calibri', size=8, color='94a3b8', italic=True); f.alignment = Alignment(horizontal='center'); ws.row_dimensions[current_row].height = 20

    buf = io.BytesIO(); wb.save(buf); return buf.getvalue()


class CORSProxyRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Handle Proxy for Sketchfab
        if self.path.startswith('/api/sketchfab/search'):
            query_string = self.path.split('?')[-1] if '?' in self.path else ''
            target_url = f"https://api.sketchfab.com/v3/search?{query_string}"
            self.handle_proxy_request(target_url)
            return

        # Handle Proxy for Perplexity
        if self.path.startswith('/api/proxy/perplexity'):
            target_url = "https://api.perplexity.ai/chat/completions"
            self.handle_proxy_post(target_url)
            return

        # Handle Proxy for Gemini
        if self.path.startswith('/api/proxy/gemini'):
            # Extracts the full target URL from the query or just appends the query
            parsed = urllib.parse.urlparse(self.path)
            query = parsed.query
            target_url = f"https://generativelanguage.googleapis.com/{parsed.path.replace('/api/proxy/gemini/', '')}?{query}"
            self.handle_proxy_post(target_url)
            return

        # Handle Proxy for Groq
        if self.path.startswith('/api/proxy/groq'):
            target_url = "https://api.groq.com/openai/v1/chat/completions"
            self.handle_proxy_post(target_url)
            return

        # Handle Proxy for OpenRouter
        if self.path.startswith('/api/proxy/openrouter'):
            target_url = "https://openrouter.ai/api/v1/chat/completions"
            self.handle_proxy_post(target_url)
            return
        
        # Handle Favicon specifically
        if self.path == '/favicon.ico':
            self.path = '/logo.png'
            return super().do_GET()

        # Handle extensionless HTML URLs
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        if not path.endswith('/'):
            _, ext = os.path.splitext(path)
            if not ext:
                if os.path.exists(self.translate_path(path + '.html')):
                    self.path = path + '.html' + ('?' + parsed.query if parsed.query else '')

        # Standard serve
        super().do_GET()

    def guess_type(self, path):
        """Override MIME types for PWA files."""
        if str(path).endswith('manifest.json'):
            return 'application/manifest+json'
        if str(path).endswith('sw.js'):
            return 'application/javascript'
        return super().guess_type(path)

    def do_OPTIONS(self):
        """Handle CORS preflight for the PPT API."""
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def do_POST(self):
        """Handle POST /api/generate-* document endpoints."""

        ENDPOINTS = {
            '/api/generate-ppt': {
                'fn': generate_pptx_bytes,
                'ext': 'pptx',
                'mime': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            },
            '/api/generate-pdf': {
                'fn': generate_pdf_bytes,
                'ext': 'pdf',
                'mime': 'application/pdf',
            },
            '/api/generate-docx': {
                'fn': generate_docx_bytes,
                'ext': 'docx',
                'mime': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            },
            '/api/generate-xlsx': {
                'fn': generate_xlsx_bytes,
                'ext': 'xlsx',
                'mime': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            },
        }

        endpoint = ENDPOINTS.get(self.path)
        if endpoint:
            try:
                length = int(self.headers.get('Content-Length', 0))
                raw = self.rfile.read(length)
                data = json.loads(raw.decode('utf-8'))

                file_bytes = endpoint['fn'](data)

                title = data.get('title', 'Orbian_Document')
                safe_title = "".join(c if c.isalnum() or c in ' _-' else '_' for c in title).strip().replace(' ', '_')
                filename = f"{safe_title}.{endpoint['ext']}"

                self.send_response(200)
                self.send_header('Content-Type', endpoint['mime'])
                self.send_header('Content-Disposition', f'attachment; filename="{filename}"')
                self.send_header('Content-Length', str(len(file_bytes)))
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(file_bytes)

            except Exception as e:
                import traceback
                err_msg = json.dumps({"error": str(e), "trace": traceback.format_exc()}).encode()
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Content-Length', str(len(err_msg)))
                self.end_headers()
                self.wfile.write(err_msg)
        else:
            self.send_error(404, "Not Found")

    def translate_path(self, path):
        # 1. Split out query/fragment
        path_only = path.split('?')[0].split('#')[0]
        
        # 2. SPA Routing for AI Chat: /app/anything -> app.html
        # If it's a deep path under /app and NOT a file request
        if path_only.startswith('/app/') and '.' not in os.path.basename(path_only):
            return os.path.join(os.getcwd(), 'app.html')

        # 3. Standard Translation
        translated = super().translate_path(path_only)
        
        # 4. Extensionless HTML (e.g. /auth/login -> /auth/login.html)
        if not os.path.exists(translated) and not os.path.isdir(translated):
            if '.' not in os.path.basename(path_only):
                html_path = translated + '.html'
                if os.path.exists(html_path):
                    return html_path

        # 5. Asset Fallback for SPA (e.g. /app/styles.css -> /styles.css)
        if not os.path.exists(translated):
            parts = [p for p in path_only.split('/') if p]
            if len(parts) >= 2:
                # Try finding the file in root by removing the first directory
                alt_relative = '/'.join(parts[1:])
                alt_translated = super().translate_path('/' + alt_relative)
                if os.path.exists(alt_translated):
                    return alt_translated

        return translated

    def handle_proxy_request(self, target_url):
        try:
            req = urllib.request.Request(target_url)
            # Add user agent to avoid blocking
            req.add_header('User-Agent', 'Mozilla/5.0') 

            with urllib.request.urlopen(req) as response:
                self.send_response(response.status)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(response.read())

        except urllib.error.HTTPError as e:
            self.send_response(e.code)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(e.read())
        except Exception as e:
            self.send_error(500, f"Internal Proxy Error: {str(e)}")

    def handle_proxy_post(self, target_url):
        try:
            length = int(self.headers.get('Content-Length', 0))
            body = self.rfile.read(length)
            
            req = urllib.request.Request(target_url, data=body, method='POST')
            
            # Forward relevant headers
            for header in ['Authorization', 'Content-Type', 'x-goog-api-client', 'x-goog-api-key']:
                if header in self.headers:
                    req.add_header(header, self.headers[header])
            
            # Add user agent
            req.add_header('User-Agent', 'Mozilla/5.0')

            with urllib.request.urlopen(req) as response:
                self.send_response(response.status)
                # Forward response headers (simplified)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(response.read())

        except urllib.error.HTTPError as e:
            self.send_response(e.code)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(e.read())
        except Exception as e:
            import traceback
            print(traceback.format_exc())
            self.send_error(500, f"Internal Proxy Error: {str(e)}")

def serve():
    import socket
    Handler = CORSProxyRequestHandler
    socketserver.TCPServer.allow_reuse_address = True

    # Get local network IP for phone access
    try:
        local_ip = socket.gethostbyname(socket.gethostname())
    except:
        local_ip = '192.168.x.x'

    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print(f"[OK] Orbian Server started!")
        print(f"     PC:    http://localhost:{PORT}")
        print(f"     Phone: http://{local_ip}:{PORT}  (same WiFi required)")
        print("[OK] CORS Proxy + PDF/DOCX/XLSX/PPTX API Active")
        print("[PWA] manifest.json + sw.js ready for install")
        print("Press Ctrl+C to stop.")
        
        webbrowser.open(f"http://localhost:{PORT}/")
        
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nServer stopped.")
            sys.exit(0)

if __name__ == "__main__":
    serve()
